//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrimFuel.Web.Admin.Controls.SubscriptionControl {
    
    
    public partial class Subscription {
        
        /// <summary>
        /// SubscriptionProductGroup1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TrimFuel.Web.Admin.Controls.SubscriptionControl.SubscriptionProductGroup SubscriptionProductGroup1;
        
        /// <summary>
        /// SubscriptionProduct1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TrimFuel.Web.Admin.Controls.SubscriptionControl.SubscriptionProduct SubscriptionProduct1;
        
        /// <summary>
        /// SubscriptionPlanFrequency1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TrimFuel.Web.Admin.Controls.SubscriptionControl.SubscriptionPlanFrequency SubscriptionPlanFrequency1;
        
        /// <summary>
        /// SubscriptionList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TrimFuel.Web.Admin.Controls.SubscriptionControl.SubscriptionList SubscriptionList1;
        
        /// <summary>
        /// hdnRecurringPlanID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox hdnRecurringPlanID;
    }
}
