//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecigsbrand.Store2 {
    
    
    public partial class e_cigarette_customer_service {
        
        /// <summary>
        /// cAccessories control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecigsbrand.Store2.Controls.Accessories cAccessories;
    }
}
