//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrimFuel.WebServices.Test.TutorVista {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessErrorOfChargeHistory", Namespace="http://trianglecrm.com/")]
    [System.SerializableAttribute()]
    public partial class BusinessErrorOfChargeHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrimFuel.WebServices.Test.TutorVista.ChargeHistory ReturnValueField;
        
        private TrimFuel.WebServices.Test.TutorVista.BusinessErrorState StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TrimFuel.WebServices.Test.TutorVista.ChargeHistory ReturnValue {
            get {
                return this.ReturnValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnValueField, value) != true)) {
                    this.ReturnValueField = value;
                    this.RaisePropertyChanged("ReturnValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TrimFuel.WebServices.Test.TutorVista.BusinessErrorState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChargeHistory", Namespace="http://trianglecrm.com/")]
    [System.SerializableAttribute()]
    public partial class ChargeHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> ChargeHistoryIDField;
        
        private System.Nullable<decimal> AmountField;
        
        private System.Nullable<bool> SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MIDField;
        
        private System.Nullable<System.DateTime> DateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> ChargeHistoryID {
            get {
                return this.ChargeHistoryIDField;
            }
            set {
                if ((this.ChargeHistoryIDField.Equals(value) != true)) {
                    this.ChargeHistoryIDField = value;
                    this.RaisePropertyChanged("ChargeHistoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<bool> Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MID {
            get {
                return this.MIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MIDField, value) != true)) {
                    this.MIDField = value;
                    this.RaisePropertyChanged("MID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessErrorState", Namespace="http://trianglecrm.com/")]
    public enum BusinessErrorState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessErrorOfChargeHistoryList", Namespace="http://trianglecrm.com/")]
    [System.SerializableAttribute()]
    public partial class BusinessErrorOfChargeHistoryList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrimFuel.WebServices.Test.TutorVista.ChargeHistory[] ReturnValueField;
        
        private TrimFuel.WebServices.Test.TutorVista.BusinessErrorState StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TrimFuel.WebServices.Test.TutorVista.ChargeHistory[] ReturnValue {
            get {
                return this.ReturnValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnValueField, value) != true)) {
                    this.ReturnValueField = value;
                    this.RaisePropertyChanged("ReturnValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TrimFuel.WebServices.Test.TutorVista.BusinessErrorState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://trianglecrm.com/", ConfigurationName="TutorVista.billing_wsSoap")]
    public interface billing_wsSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://trianglecrm.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trianglecrm.com/Void", ReplyAction="*")]
        TrimFuel.WebServices.Test.TutorVista.VoidResponse Void(TrimFuel.WebServices.Test.TutorVista.VoidRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://trianglecrm.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trianglecrm.com/Refund", ReplyAction="*")]
        TrimFuel.WebServices.Test.TutorVista.RefundResponse Refund(TrimFuel.WebServices.Test.TutorVista.RefundRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://trianglecrm.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trianglecrm.com/Charge", ReplyAction="*")]
        TrimFuel.WebServices.Test.TutorVista.ChargeResponse Charge(TrimFuel.WebServices.Test.TutorVista.ChargeRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://trianglecrm.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trianglecrm.com/Rebill", ReplyAction="*")]
        TrimFuel.WebServices.Test.TutorVista.RebillResponse Rebill(TrimFuel.WebServices.Test.TutorVista.RebillRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://trianglecrm.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trianglecrm.com/ChargeLookup", ReplyAction="*")]
        TrimFuel.WebServices.Test.TutorVista.ChargeLookupResponse ChargeLookup(TrimFuel.WebServices.Test.TutorVista.ChargeLookupRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://trianglecrm.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trianglecrm.com/UserLookup", ReplyAction="*")]
        TrimFuel.WebServices.Test.TutorVista.UserLookupResponse UserLookup(TrimFuel.WebServices.Test.TutorVista.UserLookupRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VoidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Void", Namespace="http://trianglecrm.com/", Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.VoidRequestBody Body;
        
        public VoidRequest() {
        }
        
        public VoidRequest(TrimFuel.WebServices.Test.TutorVista.VoidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trianglecrm.com/")]
    public partial class VoidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long chargeHistoryID;
        
        public VoidRequestBody() {
        }
        
        public VoidRequestBody(string username, string password, long chargeHistoryID) {
            this.username = username;
            this.password = password;
            this.chargeHistoryID = chargeHistoryID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VoidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VoidResponse", Namespace="http://trianglecrm.com/", Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.VoidResponseBody Body;
        
        public VoidResponse() {
        }
        
        public VoidResponse(TrimFuel.WebServices.Test.TutorVista.VoidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trianglecrm.com/")]
    public partial class VoidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory VoidResult;
        
        public VoidResponseBody() {
        }
        
        public VoidResponseBody(TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory VoidResult) {
            this.VoidResult = VoidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Refund", Namespace="http://trianglecrm.com/", Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.RefundRequestBody Body;
        
        public RefundRequest() {
        }
        
        public RefundRequest(TrimFuel.WebServices.Test.TutorVista.RefundRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trianglecrm.com/")]
    public partial class RefundRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long chargeHistoryID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal refundAmount;
        
        public RefundRequestBody() {
        }
        
        public RefundRequestBody(string username, string password, long chargeHistoryID, decimal refundAmount) {
            this.username = username;
            this.password = password;
            this.chargeHistoryID = chargeHistoryID;
            this.refundAmount = refundAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefundResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RefundResponse", Namespace="http://trianglecrm.com/", Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.RefundResponseBody Body;
        
        public RefundResponse() {
        }
        
        public RefundResponse(TrimFuel.WebServices.Test.TutorVista.RefundResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trianglecrm.com/")]
    public partial class RefundResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory RefundResult;
        
        public RefundResponseBody() {
        }
        
        public RefundResponseBody(TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory RefundResult) {
            this.RefundResult = RefundResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Charge", Namespace="http://trianglecrm.com/", Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.ChargeRequestBody Body;
        
        public ChargeRequest() {
        }
        
        public ChargeRequest(TrimFuel.WebServices.Test.TutorVista.ChargeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trianglecrm.com/")]
    public partial class ChargeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string address1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string address2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string zip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string affiliate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string subAffiliate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string internalID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public int paymentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string creditCard;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string cvv;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public int expMonth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public int expYear;
        
        public ChargeRequestBody() {
        }
        
        public ChargeRequestBody(
                    string username, 
                    string password, 
                    decimal amount, 
                    string firstName, 
                    string lastName, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zip, 
                    string phone, 
                    string email, 
                    string ip, 
                    string affiliate, 
                    string subAffiliate, 
                    string internalID, 
                    int paymentType, 
                    string creditCard, 
                    string cvv, 
                    int expMonth, 
                    int expYear) {
            this.username = username;
            this.password = password;
            this.amount = amount;
            this.firstName = firstName;
            this.lastName = lastName;
            this.address1 = address1;
            this.address2 = address2;
            this.city = city;
            this.state = state;
            this.zip = zip;
            this.phone = phone;
            this.email = email;
            this.ip = ip;
            this.affiliate = affiliate;
            this.subAffiliate = subAffiliate;
            this.internalID = internalID;
            this.paymentType = paymentType;
            this.creditCard = creditCard;
            this.cvv = cvv;
            this.expMonth = expMonth;
            this.expYear = expYear;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChargeResponse", Namespace="http://trianglecrm.com/", Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.ChargeResponseBody Body;
        
        public ChargeResponse() {
        }
        
        public ChargeResponse(TrimFuel.WebServices.Test.TutorVista.ChargeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trianglecrm.com/")]
    public partial class ChargeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory ChargeResult;
        
        public ChargeResponseBody() {
        }
        
        public ChargeResponseBody(TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory ChargeResult) {
            this.ChargeResult = ChargeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RebillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Rebill", Namespace="http://trianglecrm.com/", Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.RebillRequestBody Body;
        
        public RebillRequest() {
        }
        
        public RebillRequest(TrimFuel.WebServices.Test.TutorVista.RebillRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trianglecrm.com/")]
    public partial class RebillRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string internalID;
        
        public RebillRequestBody() {
        }
        
        public RebillRequestBody(string username, string password, decimal amount, string internalID) {
            this.username = username;
            this.password = password;
            this.amount = amount;
            this.internalID = internalID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RebillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RebillResponse", Namespace="http://trianglecrm.com/", Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.RebillResponseBody Body;
        
        public RebillResponse() {
        }
        
        public RebillResponse(TrimFuel.WebServices.Test.TutorVista.RebillResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trianglecrm.com/")]
    public partial class RebillResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory RebillResult;
        
        public RebillResponseBody() {
        }
        
        public RebillResponseBody(TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory RebillResult) {
            this.RebillResult = RebillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeLookupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChargeLookup", Namespace="http://trianglecrm.com/", Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.ChargeLookupRequestBody Body;
        
        public ChargeLookupRequest() {
        }
        
        public ChargeLookupRequest(TrimFuel.WebServices.Test.TutorVista.ChargeLookupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trianglecrm.com/")]
    public partial class ChargeLookupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long chargeHistoryID;
        
        public ChargeLookupRequestBody() {
        }
        
        public ChargeLookupRequestBody(string username, string password, long chargeHistoryID) {
            this.username = username;
            this.password = password;
            this.chargeHistoryID = chargeHistoryID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeLookupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChargeLookupResponse", Namespace="http://trianglecrm.com/", Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.ChargeLookupResponseBody Body;
        
        public ChargeLookupResponse() {
        }
        
        public ChargeLookupResponse(TrimFuel.WebServices.Test.TutorVista.ChargeLookupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trianglecrm.com/")]
    public partial class ChargeLookupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory ChargeLookupResult;
        
        public ChargeLookupResponseBody() {
        }
        
        public ChargeLookupResponseBody(TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory ChargeLookupResult) {
            this.ChargeLookupResult = ChargeLookupResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserLookupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserLookup", Namespace="http://trianglecrm.com/", Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.UserLookupRequestBody Body;
        
        public UserLookupRequest() {
        }
        
        public UserLookupRequest(TrimFuel.WebServices.Test.TutorVista.UserLookupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trianglecrm.com/")]
    public partial class UserLookupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string internalID;
        
        public UserLookupRequestBody() {
        }
        
        public UserLookupRequestBody(string username, string password, string internalID) {
            this.username = username;
            this.password = password;
            this.internalID = internalID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserLookupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserLookupResponse", Namespace="http://trianglecrm.com/", Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.UserLookupResponseBody Body;
        
        public UserLookupResponse() {
        }
        
        public UserLookupResponse(TrimFuel.WebServices.Test.TutorVista.UserLookupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trianglecrm.com/")]
    public partial class UserLookupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistoryList UserLookupResult;
        
        public UserLookupResponseBody() {
        }
        
        public UserLookupResponseBody(TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistoryList UserLookupResult) {
            this.UserLookupResult = UserLookupResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface billing_wsSoapChannel : TrimFuel.WebServices.Test.TutorVista.billing_wsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class billing_wsSoapClient : System.ServiceModel.ClientBase<TrimFuel.WebServices.Test.TutorVista.billing_wsSoap>, TrimFuel.WebServices.Test.TutorVista.billing_wsSoap {
        
        public billing_wsSoapClient() {
        }
        
        public billing_wsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public billing_wsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public billing_wsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public billing_wsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrimFuel.WebServices.Test.TutorVista.VoidResponse TrimFuel.WebServices.Test.TutorVista.billing_wsSoap.Void(TrimFuel.WebServices.Test.TutorVista.VoidRequest request) {
            return base.Channel.Void(request);
        }
        
        public TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory Void(string username, string password, long chargeHistoryID) {
            TrimFuel.WebServices.Test.TutorVista.VoidRequest inValue = new TrimFuel.WebServices.Test.TutorVista.VoidRequest();
            inValue.Body = new TrimFuel.WebServices.Test.TutorVista.VoidRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.chargeHistoryID = chargeHistoryID;
            TrimFuel.WebServices.Test.TutorVista.VoidResponse retVal = ((TrimFuel.WebServices.Test.TutorVista.billing_wsSoap)(this)).Void(inValue);
            return retVal.Body.VoidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrimFuel.WebServices.Test.TutorVista.RefundResponse TrimFuel.WebServices.Test.TutorVista.billing_wsSoap.Refund(TrimFuel.WebServices.Test.TutorVista.RefundRequest request) {
            return base.Channel.Refund(request);
        }
        
        public TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory Refund(string username, string password, long chargeHistoryID, decimal refundAmount) {
            TrimFuel.WebServices.Test.TutorVista.RefundRequest inValue = new TrimFuel.WebServices.Test.TutorVista.RefundRequest();
            inValue.Body = new TrimFuel.WebServices.Test.TutorVista.RefundRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.chargeHistoryID = chargeHistoryID;
            inValue.Body.refundAmount = refundAmount;
            TrimFuel.WebServices.Test.TutorVista.RefundResponse retVal = ((TrimFuel.WebServices.Test.TutorVista.billing_wsSoap)(this)).Refund(inValue);
            return retVal.Body.RefundResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrimFuel.WebServices.Test.TutorVista.ChargeResponse TrimFuel.WebServices.Test.TutorVista.billing_wsSoap.Charge(TrimFuel.WebServices.Test.TutorVista.ChargeRequest request) {
            return base.Channel.Charge(request);
        }
        
        public TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory Charge(
                    string username, 
                    string password, 
                    decimal amount, 
                    string firstName, 
                    string lastName, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zip, 
                    string phone, 
                    string email, 
                    string ip, 
                    string affiliate, 
                    string subAffiliate, 
                    string internalID, 
                    int paymentType, 
                    string creditCard, 
                    string cvv, 
                    int expMonth, 
                    int expYear) {
            TrimFuel.WebServices.Test.TutorVista.ChargeRequest inValue = new TrimFuel.WebServices.Test.TutorVista.ChargeRequest();
            inValue.Body = new TrimFuel.WebServices.Test.TutorVista.ChargeRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.amount = amount;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.address1 = address1;
            inValue.Body.address2 = address2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip = zip;
            inValue.Body.phone = phone;
            inValue.Body.email = email;
            inValue.Body.ip = ip;
            inValue.Body.affiliate = affiliate;
            inValue.Body.subAffiliate = subAffiliate;
            inValue.Body.internalID = internalID;
            inValue.Body.paymentType = paymentType;
            inValue.Body.creditCard = creditCard;
            inValue.Body.cvv = cvv;
            inValue.Body.expMonth = expMonth;
            inValue.Body.expYear = expYear;
            TrimFuel.WebServices.Test.TutorVista.ChargeResponse retVal = ((TrimFuel.WebServices.Test.TutorVista.billing_wsSoap)(this)).Charge(inValue);
            return retVal.Body.ChargeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrimFuel.WebServices.Test.TutorVista.RebillResponse TrimFuel.WebServices.Test.TutorVista.billing_wsSoap.Rebill(TrimFuel.WebServices.Test.TutorVista.RebillRequest request) {
            return base.Channel.Rebill(request);
        }
        
        public TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory Rebill(string username, string password, decimal amount, string internalID) {
            TrimFuel.WebServices.Test.TutorVista.RebillRequest inValue = new TrimFuel.WebServices.Test.TutorVista.RebillRequest();
            inValue.Body = new TrimFuel.WebServices.Test.TutorVista.RebillRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.amount = amount;
            inValue.Body.internalID = internalID;
            TrimFuel.WebServices.Test.TutorVista.RebillResponse retVal = ((TrimFuel.WebServices.Test.TutorVista.billing_wsSoap)(this)).Rebill(inValue);
            return retVal.Body.RebillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrimFuel.WebServices.Test.TutorVista.ChargeLookupResponse TrimFuel.WebServices.Test.TutorVista.billing_wsSoap.ChargeLookup(TrimFuel.WebServices.Test.TutorVista.ChargeLookupRequest request) {
            return base.Channel.ChargeLookup(request);
        }
        
        public TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistory ChargeLookup(string username, string password, long chargeHistoryID) {
            TrimFuel.WebServices.Test.TutorVista.ChargeLookupRequest inValue = new TrimFuel.WebServices.Test.TutorVista.ChargeLookupRequest();
            inValue.Body = new TrimFuel.WebServices.Test.TutorVista.ChargeLookupRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.chargeHistoryID = chargeHistoryID;
            TrimFuel.WebServices.Test.TutorVista.ChargeLookupResponse retVal = ((TrimFuel.WebServices.Test.TutorVista.billing_wsSoap)(this)).ChargeLookup(inValue);
            return retVal.Body.ChargeLookupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrimFuel.WebServices.Test.TutorVista.UserLookupResponse TrimFuel.WebServices.Test.TutorVista.billing_wsSoap.UserLookup(TrimFuel.WebServices.Test.TutorVista.UserLookupRequest request) {
            return base.Channel.UserLookup(request);
        }
        
        public TrimFuel.WebServices.Test.TutorVista.BusinessErrorOfChargeHistoryList UserLookup(string username, string password, string internalID) {
            TrimFuel.WebServices.Test.TutorVista.UserLookupRequest inValue = new TrimFuel.WebServices.Test.TutorVista.UserLookupRequest();
            inValue.Body = new TrimFuel.WebServices.Test.TutorVista.UserLookupRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.internalID = internalID;
            TrimFuel.WebServices.Test.TutorVista.UserLookupResponse retVal = ((TrimFuel.WebServices.Test.TutorVista.billing_wsSoap)(this)).UserLookup(inValue);
            return retVal.Body.UserLookupResult;
        }
    }
}
