//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
// 
#pragma warning disable 1591

namespace TrimFuel.Business.PagadorWService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PagadorSoap", Namespace="https://www.pagador.com.br/webservice/pagador")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractData))]
    public partial class Pagador : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AuthorizeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthorizeWithDateFirstInstallmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthorizeMobileOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthorizeMobilePartialOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthorizeWithServiceTaxOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthorizeAvsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthorizeAvsStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoidTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoidPartialOperationCompleted;
        
        private System.Threading.SendOrPostCallback OneDollarAuthOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthorizeExistingAvsStatusWithServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback CaptureOperationCompleted;
        
        private System.Threading.SendOrPostCallback CapturePartialOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateTransactionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Pagador() {
            this.Url = global::TrimFuel.Business.Properties.Settings.Default.TrimFuel_Business_Pagador_Pagador;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AuthorizeCompletedEventHandler AuthorizeCompleted;
        
        /// <remarks/>
        public event AuthorizeWithDateFirstInstallmentCompletedEventHandler AuthorizeWithDateFirstInstallmentCompleted;
        
        /// <remarks/>
        public event AuthorizeMobileCompletedEventHandler AuthorizeMobileCompleted;
        
        /// <remarks/>
        public event AuthorizeMobilePartialCompletedEventHandler AuthorizeMobilePartialCompleted;
        
        /// <remarks/>
        public event AuthorizeWithServiceTaxCompletedEventHandler AuthorizeWithServiceTaxCompleted;
        
        /// <remarks/>
        public event AuthorizeAvsCompletedEventHandler AuthorizeAvsCompleted;
        
        /// <remarks/>
        public event AuthorizeAvsStatusCompletedEventHandler AuthorizeAvsStatusCompleted;
        
        /// <remarks/>
        public event VoidTransactionCompletedEventHandler VoidTransactionCompleted;
        
        /// <remarks/>
        public event VoidPartialCompletedEventHandler VoidPartialCompleted;
        
        /// <remarks/>
        public event OneDollarAuthCompletedEventHandler OneDollarAuthCompleted;
        
        /// <remarks/>
        public event AuthorizeExistingAvsStatusWithServiceCompletedEventHandler AuthorizeExistingAvsStatusWithServiceCompleted;
        
        /// <remarks/>
        public event CaptureCompletedEventHandler CaptureCompleted;
        
        /// <remarks/>
        public event CapturePartialCompletedEventHandler CapturePartialCompleted;
        
        /// <remarks/>
        public event CreateTransactionCompletedEventHandler CreateTransactionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pagador.com.br/webservice/pagador/Authorize", RequestNamespace="https://www.pagador.com.br/webservice/pagador", ResponseNamespace="https://www.pagador.com.br/webservice/pagador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagadorReturn Authorize(string merchantId, string orderId, string customerName, string amount, string paymentMethod, string holder, string cardNumber, string expiration, string securityCode, string numberPayments, string typePayment) {
            object[] results = this.Invoke("Authorize", new object[] {
                        merchantId,
                        orderId,
                        customerName,
                        amount,
                        paymentMethod,
                        holder,
                        cardNumber,
                        expiration,
                        securityCode,
                        numberPayments,
                        typePayment});
            return ((PagadorReturn)(results[0]));
        }
        
        /// <remarks/>
        public void AuthorizeAsync(string merchantId, string orderId, string customerName, string amount, string paymentMethod, string holder, string cardNumber, string expiration, string securityCode, string numberPayments, string typePayment) {
            this.AuthorizeAsync(merchantId, orderId, customerName, amount, paymentMethod, holder, cardNumber, expiration, securityCode, numberPayments, typePayment, null);
        }
        
        /// <remarks/>
        public void AuthorizeAsync(string merchantId, string orderId, string customerName, string amount, string paymentMethod, string holder, string cardNumber, string expiration, string securityCode, string numberPayments, string typePayment, object userState) {
            if ((this.AuthorizeOperationCompleted == null)) {
                this.AuthorizeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthorizeOperationCompleted);
            }
            this.InvokeAsync("Authorize", new object[] {
                        merchantId,
                        orderId,
                        customerName,
                        amount,
                        paymentMethod,
                        holder,
                        cardNumber,
                        expiration,
                        securityCode,
                        numberPayments,
                        typePayment}, this.AuthorizeOperationCompleted, userState);
        }
        
        private void OnAuthorizeOperationCompleted(object arg) {
            if ((this.AuthorizeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthorizeCompleted(this, new AuthorizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pagador.com.br/webservice/pagador/AuthorizeWithDateFirstInstallment", RequestNamespace="https://www.pagador.com.br/webservice/pagador", ResponseNamespace="https://www.pagador.com.br/webservice/pagador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagadorReturn AuthorizeWithDateFirstInstallment(AuthorizeWithDateFirstInstallmentRequest authorizeWithDateFirstInstallmentRequest) {
            object[] results = this.Invoke("AuthorizeWithDateFirstInstallment", new object[] {
                        authorizeWithDateFirstInstallmentRequest});
            return ((PagadorReturn)(results[0]));
        }
        
        /// <remarks/>
        public void AuthorizeWithDateFirstInstallmentAsync(AuthorizeWithDateFirstInstallmentRequest authorizeWithDateFirstInstallmentRequest) {
            this.AuthorizeWithDateFirstInstallmentAsync(authorizeWithDateFirstInstallmentRequest, null);
        }
        
        /// <remarks/>
        public void AuthorizeWithDateFirstInstallmentAsync(AuthorizeWithDateFirstInstallmentRequest authorizeWithDateFirstInstallmentRequest, object userState) {
            if ((this.AuthorizeWithDateFirstInstallmentOperationCompleted == null)) {
                this.AuthorizeWithDateFirstInstallmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthorizeWithDateFirstInstallmentOperationCompleted);
            }
            this.InvokeAsync("AuthorizeWithDateFirstInstallment", new object[] {
                        authorizeWithDateFirstInstallmentRequest}, this.AuthorizeWithDateFirstInstallmentOperationCompleted, userState);
        }
        
        private void OnAuthorizeWithDateFirstInstallmentOperationCompleted(object arg) {
            if ((this.AuthorizeWithDateFirstInstallmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthorizeWithDateFirstInstallmentCompleted(this, new AuthorizeWithDateFirstInstallmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pagador.com.br/webservice/pagador/AuthorizeMobile", RequestNamespace="https://www.pagador.com.br/webservice/pagador", ResponseNamespace="https://www.pagador.com.br/webservice/pagador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagadorReturn AuthorizeMobile(string merchantId, string orderId, string customerName, string customerMobile, string amount, string paymentMethod, string numberPayments, string typePayment) {
            object[] results = this.Invoke("AuthorizeMobile", new object[] {
                        merchantId,
                        orderId,
                        customerName,
                        customerMobile,
                        amount,
                        paymentMethod,
                        numberPayments,
                        typePayment});
            return ((PagadorReturn)(results[0]));
        }
        
        /// <remarks/>
        public void AuthorizeMobileAsync(string merchantId, string orderId, string customerName, string customerMobile, string amount, string paymentMethod, string numberPayments, string typePayment) {
            this.AuthorizeMobileAsync(merchantId, orderId, customerName, customerMobile, amount, paymentMethod, numberPayments, typePayment, null);
        }
        
        /// <remarks/>
        public void AuthorizeMobileAsync(string merchantId, string orderId, string customerName, string customerMobile, string amount, string paymentMethod, string numberPayments, string typePayment, object userState) {
            if ((this.AuthorizeMobileOperationCompleted == null)) {
                this.AuthorizeMobileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthorizeMobileOperationCompleted);
            }
            this.InvokeAsync("AuthorizeMobile", new object[] {
                        merchantId,
                        orderId,
                        customerName,
                        customerMobile,
                        amount,
                        paymentMethod,
                        numberPayments,
                        typePayment}, this.AuthorizeMobileOperationCompleted, userState);
        }
        
        private void OnAuthorizeMobileOperationCompleted(object arg) {
            if ((this.AuthorizeMobileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthorizeMobileCompleted(this, new AuthorizeMobileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pagador.com.br/webservice/pagador/AuthorizeMobilePartial", RequestNamespace="https://www.pagador.com.br/webservice/pagador", ResponseNamespace="https://www.pagador.com.br/webservice/pagador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagadorReturn AuthorizeMobilePartial(string transactionId, string mobile, string typePayment) {
            object[] results = this.Invoke("AuthorizeMobilePartial", new object[] {
                        transactionId,
                        mobile,
                        typePayment});
            return ((PagadorReturn)(results[0]));
        }
        
        /// <remarks/>
        public void AuthorizeMobilePartialAsync(string transactionId, string mobile, string typePayment) {
            this.AuthorizeMobilePartialAsync(transactionId, mobile, typePayment, null);
        }
        
        /// <remarks/>
        public void AuthorizeMobilePartialAsync(string transactionId, string mobile, string typePayment, object userState) {
            if ((this.AuthorizeMobilePartialOperationCompleted == null)) {
                this.AuthorizeMobilePartialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthorizeMobilePartialOperationCompleted);
            }
            this.InvokeAsync("AuthorizeMobilePartial", new object[] {
                        transactionId,
                        mobile,
                        typePayment}, this.AuthorizeMobilePartialOperationCompleted, userState);
        }
        
        private void OnAuthorizeMobilePartialOperationCompleted(object arg) {
            if ((this.AuthorizeMobilePartialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthorizeMobilePartialCompleted(this, new AuthorizeMobilePartialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pagador.com.br/webservice/pagador/AuthorizeWithServiceTax", RequestNamespace="https://www.pagador.com.br/webservice/pagador", ResponseNamespace="https://www.pagador.com.br/webservice/pagador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagadorReturn AuthorizeWithServiceTax(string merchantId, string orderId, string customerName, string amount, string serviceTax, string paymentMethod, string holder, string cardNumber, string expiration, string securityCode, string numberPayments, string typePayment) {
            object[] results = this.Invoke("AuthorizeWithServiceTax", new object[] {
                        merchantId,
                        orderId,
                        customerName,
                        amount,
                        serviceTax,
                        paymentMethod,
                        holder,
                        cardNumber,
                        expiration,
                        securityCode,
                        numberPayments,
                        typePayment});
            return ((PagadorReturn)(results[0]));
        }
        
        /// <remarks/>
        public void AuthorizeWithServiceTaxAsync(string merchantId, string orderId, string customerName, string amount, string serviceTax, string paymentMethod, string holder, string cardNumber, string expiration, string securityCode, string numberPayments, string typePayment) {
            this.AuthorizeWithServiceTaxAsync(merchantId, orderId, customerName, amount, serviceTax, paymentMethod, holder, cardNumber, expiration, securityCode, numberPayments, typePayment, null);
        }
        
        /// <remarks/>
        public void AuthorizeWithServiceTaxAsync(string merchantId, string orderId, string customerName, string amount, string serviceTax, string paymentMethod, string holder, string cardNumber, string expiration, string securityCode, string numberPayments, string typePayment, object userState) {
            if ((this.AuthorizeWithServiceTaxOperationCompleted == null)) {
                this.AuthorizeWithServiceTaxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthorizeWithServiceTaxOperationCompleted);
            }
            this.InvokeAsync("AuthorizeWithServiceTax", new object[] {
                        merchantId,
                        orderId,
                        customerName,
                        amount,
                        serviceTax,
                        paymentMethod,
                        holder,
                        cardNumber,
                        expiration,
                        securityCode,
                        numberPayments,
                        typePayment}, this.AuthorizeWithServiceTaxOperationCompleted, userState);
        }
        
        private void OnAuthorizeWithServiceTaxOperationCompleted(object arg) {
            if ((this.AuthorizeWithServiceTaxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthorizeWithServiceTaxCompleted(this, new AuthorizeWithServiceTaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pagador.com.br/webservice/pagador/AuthorizeAvs", RequestNamespace="https://www.pagador.com.br/webservice/pagador", ResponseNamespace="https://www.pagador.com.br/webservice/pagador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagadorAvsReturn AuthorizeAvs(
                    string merchantId, 
                    string orderId, 
                    string customerName, 
                    string amount, 
                    string paymentMethod, 
                    string holder, 
                    string cardNumber, 
                    string expiration, 
                    string securityCode, 
                    string numberPayments, 
                    string typePayment, 
                    string cpf, 
                    string address, 
                    string addressNumber, 
                    string addressComplement, 
                    string zipCode1, 
                    string zipCode2, 
                    string city, 
                    string state, 
                    string country) {
            object[] results = this.Invoke("AuthorizeAvs", new object[] {
                        merchantId,
                        orderId,
                        customerName,
                        amount,
                        paymentMethod,
                        holder,
                        cardNumber,
                        expiration,
                        securityCode,
                        numberPayments,
                        typePayment,
                        cpf,
                        address,
                        addressNumber,
                        addressComplement,
                        zipCode1,
                        zipCode2,
                        city,
                        state,
                        country});
            return ((PagadorAvsReturn)(results[0]));
        }
        
        /// <remarks/>
        public void AuthorizeAvsAsync(
                    string merchantId, 
                    string orderId, 
                    string customerName, 
                    string amount, 
                    string paymentMethod, 
                    string holder, 
                    string cardNumber, 
                    string expiration, 
                    string securityCode, 
                    string numberPayments, 
                    string typePayment, 
                    string cpf, 
                    string address, 
                    string addressNumber, 
                    string addressComplement, 
                    string zipCode1, 
                    string zipCode2, 
                    string city, 
                    string state, 
                    string country) {
            this.AuthorizeAvsAsync(merchantId, orderId, customerName, amount, paymentMethod, holder, cardNumber, expiration, securityCode, numberPayments, typePayment, cpf, address, addressNumber, addressComplement, zipCode1, zipCode2, city, state, country, null);
        }
        
        /// <remarks/>
        public void AuthorizeAvsAsync(
                    string merchantId, 
                    string orderId, 
                    string customerName, 
                    string amount, 
                    string paymentMethod, 
                    string holder, 
                    string cardNumber, 
                    string expiration, 
                    string securityCode, 
                    string numberPayments, 
                    string typePayment, 
                    string cpf, 
                    string address, 
                    string addressNumber, 
                    string addressComplement, 
                    string zipCode1, 
                    string zipCode2, 
                    string city, 
                    string state, 
                    string country, 
                    object userState) {
            if ((this.AuthorizeAvsOperationCompleted == null)) {
                this.AuthorizeAvsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthorizeAvsOperationCompleted);
            }
            this.InvokeAsync("AuthorizeAvs", new object[] {
                        merchantId,
                        orderId,
                        customerName,
                        amount,
                        paymentMethod,
                        holder,
                        cardNumber,
                        expiration,
                        securityCode,
                        numberPayments,
                        typePayment,
                        cpf,
                        address,
                        addressNumber,
                        addressComplement,
                        zipCode1,
                        zipCode2,
                        city,
                        state,
                        country}, this.AuthorizeAvsOperationCompleted, userState);
        }
        
        private void OnAuthorizeAvsOperationCompleted(object arg) {
            if ((this.AuthorizeAvsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthorizeAvsCompleted(this, new AuthorizeAvsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pagador.com.br/webservice/pagador/AuthorizeAvsStatus", RequestNamespace="https://www.pagador.com.br/webservice/pagador", ResponseNamespace="https://www.pagador.com.br/webservice/pagador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagadorAvsReturn AuthorizeAvsStatus(
                    string merchantId, 
                    string orderId, 
                    string customerName, 
                    string amount, 
                    string paymentMethod, 
                    string holder, 
                    string cardNumber, 
                    string expiration, 
                    string securityCode, 
                    string numberPayments, 
                    string typePayment, 
                    string cpf, 
                    string address, 
                    string addressNumber, 
                    string addressComplement, 
                    string zipCode1, 
                    string zipCode2, 
                    string city, 
                    string state, 
                    string country, 
                    string avsStatus) {
            object[] results = this.Invoke("AuthorizeAvsStatus", new object[] {
                        merchantId,
                        orderId,
                        customerName,
                        amount,
                        paymentMethod,
                        holder,
                        cardNumber,
                        expiration,
                        securityCode,
                        numberPayments,
                        typePayment,
                        cpf,
                        address,
                        addressNumber,
                        addressComplement,
                        zipCode1,
                        zipCode2,
                        city,
                        state,
                        country,
                        avsStatus});
            return ((PagadorAvsReturn)(results[0]));
        }
        
        /// <remarks/>
        public void AuthorizeAvsStatusAsync(
                    string merchantId, 
                    string orderId, 
                    string customerName, 
                    string amount, 
                    string paymentMethod, 
                    string holder, 
                    string cardNumber, 
                    string expiration, 
                    string securityCode, 
                    string numberPayments, 
                    string typePayment, 
                    string cpf, 
                    string address, 
                    string addressNumber, 
                    string addressComplement, 
                    string zipCode1, 
                    string zipCode2, 
                    string city, 
                    string state, 
                    string country, 
                    string avsStatus) {
            this.AuthorizeAvsStatusAsync(merchantId, orderId, customerName, amount, paymentMethod, holder, cardNumber, expiration, securityCode, numberPayments, typePayment, cpf, address, addressNumber, addressComplement, zipCode1, zipCode2, city, state, country, avsStatus, null);
        }
        
        /// <remarks/>
        public void AuthorizeAvsStatusAsync(
                    string merchantId, 
                    string orderId, 
                    string customerName, 
                    string amount, 
                    string paymentMethod, 
                    string holder, 
                    string cardNumber, 
                    string expiration, 
                    string securityCode, 
                    string numberPayments, 
                    string typePayment, 
                    string cpf, 
                    string address, 
                    string addressNumber, 
                    string addressComplement, 
                    string zipCode1, 
                    string zipCode2, 
                    string city, 
                    string state, 
                    string country, 
                    string avsStatus, 
                    object userState) {
            if ((this.AuthorizeAvsStatusOperationCompleted == null)) {
                this.AuthorizeAvsStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthorizeAvsStatusOperationCompleted);
            }
            this.InvokeAsync("AuthorizeAvsStatus", new object[] {
                        merchantId,
                        orderId,
                        customerName,
                        amount,
                        paymentMethod,
                        holder,
                        cardNumber,
                        expiration,
                        securityCode,
                        numberPayments,
                        typePayment,
                        cpf,
                        address,
                        addressNumber,
                        addressComplement,
                        zipCode1,
                        zipCode2,
                        city,
                        state,
                        country,
                        avsStatus}, this.AuthorizeAvsStatusOperationCompleted, userState);
        }
        
        private void OnAuthorizeAvsStatusOperationCompleted(object arg) {
            if ((this.AuthorizeAvsStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthorizeAvsStatusCompleted(this, new AuthorizeAvsStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pagador.com.br/webservice/pagador/VoidTransaction", RequestNamespace="https://www.pagador.com.br/webservice/pagador", ResponseNamespace="https://www.pagador.com.br/webservice/pagador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagadorVoidReturn VoidTransaction(string merchantId, string order) {
            object[] results = this.Invoke("VoidTransaction", new object[] {
                        merchantId,
                        order});
            return ((PagadorVoidReturn)(results[0]));
        }
        
        /// <remarks/>
        public void VoidTransactionAsync(string merchantId, string order) {
            this.VoidTransactionAsync(merchantId, order, null);
        }
        
        /// <remarks/>
        public void VoidTransactionAsync(string merchantId, string order, object userState) {
            if ((this.VoidTransactionOperationCompleted == null)) {
                this.VoidTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoidTransactionOperationCompleted);
            }
            this.InvokeAsync("VoidTransaction", new object[] {
                        merchantId,
                        order}, this.VoidTransactionOperationCompleted, userState);
        }
        
        private void OnVoidTransactionOperationCompleted(object arg) {
            if ((this.VoidTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoidTransactionCompleted(this, new VoidTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pagador.com.br/webservice/pagador/VoidPartial", RequestNamespace="https://www.pagador.com.br/webservice/pagador", ResponseNamespace="https://www.pagador.com.br/webservice/pagador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagadorVoidReturn VoidPartial(string merchantId, string order, string amount) {
            object[] results = this.Invoke("VoidPartial", new object[] {
                        merchantId,
                        order,
                        amount});
            return ((PagadorVoidReturn)(results[0]));
        }
        
        /// <remarks/>
        public void VoidPartialAsync(string merchantId, string order, string amount) {
            this.VoidPartialAsync(merchantId, order, amount, null);
        }
        
        /// <remarks/>
        public void VoidPartialAsync(string merchantId, string order, string amount, object userState) {
            if ((this.VoidPartialOperationCompleted == null)) {
                this.VoidPartialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoidPartialOperationCompleted);
            }
            this.InvokeAsync("VoidPartial", new object[] {
                        merchantId,
                        order,
                        amount}, this.VoidPartialOperationCompleted, userState);
        }
        
        private void OnVoidPartialOperationCompleted(object arg) {
            if ((this.VoidPartialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoidPartialCompleted(this, new VoidPartialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pagador.com.br/webservice/pagador/OneDollarAuth", RequestNamespace="https://www.pagador.com.br/webservice/pagador", ResponseNamespace="https://www.pagador.com.br/webservice/pagador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PagadorOneDollarAuthResponse", IsNullable=true)]
        public PagadorOneDollarAuthResponse OneDollarAuth([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] PagadorOneDollarAuthRequest PagadorOneDollarAuthRequest) {
            object[] results = this.Invoke("OneDollarAuth", new object[] {
                        PagadorOneDollarAuthRequest});
            return ((PagadorOneDollarAuthResponse)(results[0]));
        }
        
        /// <remarks/>
        public void OneDollarAuthAsync(PagadorOneDollarAuthRequest PagadorOneDollarAuthRequest) {
            this.OneDollarAuthAsync(PagadorOneDollarAuthRequest, null);
        }
        
        /// <remarks/>
        public void OneDollarAuthAsync(PagadorOneDollarAuthRequest PagadorOneDollarAuthRequest, object userState) {
            if ((this.OneDollarAuthOperationCompleted == null)) {
                this.OneDollarAuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOneDollarAuthOperationCompleted);
            }
            this.InvokeAsync("OneDollarAuth", new object[] {
                        PagadorOneDollarAuthRequest}, this.OneDollarAuthOperationCompleted, userState);
        }
        
        private void OnOneDollarAuthOperationCompleted(object arg) {
            if ((this.OneDollarAuthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OneDollarAuthCompleted(this, new OneDollarAuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pagador.com.br/webservice/pagador/AuthorizeExistingAvsStatusWithServi" +
            "ce", RequestNamespace="https://www.pagador.com.br/webservice/pagador", ResponseNamespace="https://www.pagador.com.br/webservice/pagador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagadorReturnWithService AuthorizeExistingAvsStatusWithService(
                    string transId, 
                    string holder, 
                    string cardNumber, 
                    string expiration, 
                    string securityCode, 
                    string numberPayments, 
                    string typePayment, 
                    string cpf, 
                    string address, 
                    string addressNumber, 
                    string addressComplement, 
                    string zipCode1, 
                    string zipCode2, 
                    string city, 
                    string state, 
                    string country, 
                    string avsStatus, 
                    bool avs, 
                    string serviceAmount) {
            object[] results = this.Invoke("AuthorizeExistingAvsStatusWithService", new object[] {
                        transId,
                        holder,
                        cardNumber,
                        expiration,
                        securityCode,
                        numberPayments,
                        typePayment,
                        cpf,
                        address,
                        addressNumber,
                        addressComplement,
                        zipCode1,
                        zipCode2,
                        city,
                        state,
                        country,
                        avsStatus,
                        avs,
                        serviceAmount});
            return ((PagadorReturnWithService)(results[0]));
        }
        
        /// <remarks/>
        public void AuthorizeExistingAvsStatusWithServiceAsync(
                    string transId, 
                    string holder, 
                    string cardNumber, 
                    string expiration, 
                    string securityCode, 
                    string numberPayments, 
                    string typePayment, 
                    string cpf, 
                    string address, 
                    string addressNumber, 
                    string addressComplement, 
                    string zipCode1, 
                    string zipCode2, 
                    string city, 
                    string state, 
                    string country, 
                    string avsStatus, 
                    bool avs, 
                    string serviceAmount) {
            this.AuthorizeExistingAvsStatusWithServiceAsync(transId, holder, cardNumber, expiration, securityCode, numberPayments, typePayment, cpf, address, addressNumber, addressComplement, zipCode1, zipCode2, city, state, country, avsStatus, avs, serviceAmount, null);
        }
        
        /// <remarks/>
        public void AuthorizeExistingAvsStatusWithServiceAsync(
                    string transId, 
                    string holder, 
                    string cardNumber, 
                    string expiration, 
                    string securityCode, 
                    string numberPayments, 
                    string typePayment, 
                    string cpf, 
                    string address, 
                    string addressNumber, 
                    string addressComplement, 
                    string zipCode1, 
                    string zipCode2, 
                    string city, 
                    string state, 
                    string country, 
                    string avsStatus, 
                    bool avs, 
                    string serviceAmount, 
                    object userState) {
            if ((this.AuthorizeExistingAvsStatusWithServiceOperationCompleted == null)) {
                this.AuthorizeExistingAvsStatusWithServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthorizeExistingAvsStatusWithServiceOperationCompleted);
            }
            this.InvokeAsync("AuthorizeExistingAvsStatusWithService", new object[] {
                        transId,
                        holder,
                        cardNumber,
                        expiration,
                        securityCode,
                        numberPayments,
                        typePayment,
                        cpf,
                        address,
                        addressNumber,
                        addressComplement,
                        zipCode1,
                        zipCode2,
                        city,
                        state,
                        country,
                        avsStatus,
                        avs,
                        serviceAmount}, this.AuthorizeExistingAvsStatusWithServiceOperationCompleted, userState);
        }
        
        private void OnAuthorizeExistingAvsStatusWithServiceOperationCompleted(object arg) {
            if ((this.AuthorizeExistingAvsStatusWithServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthorizeExistingAvsStatusWithServiceCompleted(this, new AuthorizeExistingAvsStatusWithServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pagador.com.br/webservice/pagador/Capture", RequestNamespace="https://www.pagador.com.br/webservice/pagador", ResponseNamespace="https://www.pagador.com.br/webservice/pagador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagadorReturn Capture(string merchantId, string orderId) {
            object[] results = this.Invoke("Capture", new object[] {
                        merchantId,
                        orderId});
            return ((PagadorReturn)(results[0]));
        }
        
        /// <remarks/>
        public void CaptureAsync(string merchantId, string orderId) {
            this.CaptureAsync(merchantId, orderId, null);
        }
        
        /// <remarks/>
        public void CaptureAsync(string merchantId, string orderId, object userState) {
            if ((this.CaptureOperationCompleted == null)) {
                this.CaptureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCaptureOperationCompleted);
            }
            this.InvokeAsync("Capture", new object[] {
                        merchantId,
                        orderId}, this.CaptureOperationCompleted, userState);
        }
        
        private void OnCaptureOperationCompleted(object arg) {
            if ((this.CaptureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CaptureCompleted(this, new CaptureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pagador.com.br/webservice/pagador/CapturePartial", RequestNamespace="https://www.pagador.com.br/webservice/pagador", ResponseNamespace="https://www.pagador.com.br/webservice/pagador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagadorReturn CapturePartial(string merchantId, string orderId, string captureAmount) {
            object[] results = this.Invoke("CapturePartial", new object[] {
                        merchantId,
                        orderId,
                        captureAmount});
            return ((PagadorReturn)(results[0]));
        }
        
        /// <remarks/>
        public void CapturePartialAsync(string merchantId, string orderId, string captureAmount) {
            this.CapturePartialAsync(merchantId, orderId, captureAmount, null);
        }
        
        /// <remarks/>
        public void CapturePartialAsync(string merchantId, string orderId, string captureAmount, object userState) {
            if ((this.CapturePartialOperationCompleted == null)) {
                this.CapturePartialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCapturePartialOperationCompleted);
            }
            this.InvokeAsync("CapturePartial", new object[] {
                        merchantId,
                        orderId,
                        captureAmount}, this.CapturePartialOperationCompleted, userState);
        }
        
        private void OnCapturePartialOperationCompleted(object arg) {
            if ((this.CapturePartialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CapturePartialCompleted(this, new CapturePartialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pagador.com.br/webservice/pagador/CreateTransaction", RequestNamespace="https://www.pagador.com.br/webservice/pagador", ResponseNamespace="https://www.pagador.com.br/webservice/pagador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid CreateTransaction(CreateTransactionRequest request) {
            object[] results = this.Invoke("CreateTransaction", new object[] {
                        request});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public void CreateTransactionAsync(CreateTransactionRequest request) {
            this.CreateTransactionAsync(request, null);
        }
        
        /// <remarks/>
        public void CreateTransactionAsync(CreateTransactionRequest request, object userState) {
            if ((this.CreateTransactionOperationCompleted == null)) {
                this.CreateTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTransactionOperationCompleted);
            }
            this.InvokeAsync("CreateTransaction", new object[] {
                        request}, this.CreateTransactionOperationCompleted, userState);
        }
        
        private void OnCreateTransactionOperationCompleted(object arg) {
            if ((this.CreateTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTransactionCompleted(this, new CreateTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PagadorAvsReturn))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/webservice/pagador")]
    public partial class PagadorReturn {
        
        private System.Nullable<decimal> amountField;
        
        private string authorisationNumberField;
        
        private string messageField;
        
        private string returnCodeField;
        
        private System.Nullable<byte> statusField;
        
        private string transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string authorisationNumber {
            get {
                return this.authorisationNumberField;
            }
            set {
                this.authorisationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/webservice/pagador")]
    public partial class NameValue {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BuyerData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShippingData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/webservice/pagador")]
    public abstract partial class AbstractData {
        
        private string streetTypeField;
        
        private string addressField;
        
        private string numberField;
        
        private string complementField;
        
        private string neighborhoodField;
        
        private string cityField;
        
        private string zipCodeField;
        
        private string stateField;
        
        private string countryField;
        
        /// <remarks/>
        public string StreetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Complement {
            get {
                return this.complementField;
            }
            set {
                this.complementField = value;
            }
        }
        
        /// <remarks/>
        public string Neighborhood {
            get {
                return this.neighborhoodField;
            }
            set {
                this.neighborhoodField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/webservice/pagador")]
    public partial class BuyerData : AbstractData {
        
        private string nameField;
        
        private string companyNameField;
        
        private string identificationNumberField;
        
        private System.Nullable<System.DateTime> birthDateField;
        
        private string genderField;
        
        private string maritalStatusField;
        
        private string occupationField;
        
        private string phoneNumberField;
        
        private string mobilePhoneNumberField;
        
        private string faxNumberField;
        
        private string emailField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string IdentificationNumber {
            get {
                return this.identificationNumberField;
            }
            set {
                this.identificationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        public string Occupation {
            get {
                return this.occupationField;
            }
            set {
                this.occupationField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhoneNumber {
            get {
                return this.mobilePhoneNumberField;
            }
            set {
                this.mobilePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/webservice/pagador")]
    public partial class ShippingData : AbstractData {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/webservice/pagador")]
    public partial class CreateTransactionRequest {
        
        private System.Guid merchantIdField;
        
        private System.Guid paymentMethodIdField;
        
        private decimal transactionAmountField;
        
        private short installmentCountField;
        
        private string merchantTransactionIdField;
        
        private byte typePaymentField;
        
        private ShippingData shippingDataField;
        
        private BuyerData buyerDataField;
        
        private NameValue[] extraDataField;
        
        private string ipAddressField;
        
        /// <remarks/>
        public System.Guid MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid PaymentMethodId {
            get {
                return this.paymentMethodIdField;
            }
            set {
                this.paymentMethodIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal TransactionAmount {
            get {
                return this.transactionAmountField;
            }
            set {
                this.transactionAmountField = value;
            }
        }
        
        /// <remarks/>
        public short InstallmentCount {
            get {
                return this.installmentCountField;
            }
            set {
                this.installmentCountField = value;
            }
        }
        
        /// <remarks/>
        public string MerchantTransactionId {
            get {
                return this.merchantTransactionIdField;
            }
            set {
                this.merchantTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        public byte TypePayment {
            get {
                return this.typePaymentField;
            }
            set {
                this.typePaymentField = value;
            }
        }
        
        /// <remarks/>
        public ShippingData ShippingData {
            get {
                return this.shippingDataField;
            }
            set {
                this.shippingDataField = value;
            }
        }
        
        /// <remarks/>
        public BuyerData BuyerData {
            get {
                return this.buyerDataField;
            }
            set {
                this.buyerDataField = value;
            }
        }
        
        /// <remarks/>
        public NameValue[] ExtraData {
            get {
                return this.extraDataField;
            }
            set {
                this.extraDataField = value;
            }
        }
        
        /// <remarks/>
        public string IpAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/webservice/pagador")]
    public partial class PagadorReturnWithService {
        
        private PagadorReturn mainReturnField;
        
        private PagadorReturn serviceReturnField;
        
        /// <remarks/>
        public PagadorReturn MainReturn {
            get {
                return this.mainReturnField;
            }
            set {
                this.mainReturnField = value;
            }
        }
        
        /// <remarks/>
        public PagadorReturn ServiceReturn {
            get {
                return this.serviceReturnField;
            }
            set {
                this.serviceReturnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/webservice/pagador")]
    public partial class PagadorOneDollarAuthResponse {
        
        private System.Nullable<int> amountField;
        
        private string authorizationNumberField;
        
        private string messageField;
        
        private string returnCodeField;
        
        private System.Nullable<byte> statusField;
        
        private string transactionIdField;
        
        private string avsMessageField;
        
        private string avsReturnCodeField;
        
        private System.Nullable<byte> avsStatusField;
        
        private System.Nullable<int> cancelAmountField;
        
        private string cancelOrderIdField;
        
        private string cancelMessageField;
        
        private string cancelReturnCodeField;
        
        private System.Nullable<byte> cancelStatusField;
        
        private string cancelTransactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorizationNumber {
            get {
                return this.authorizationNumberField;
            }
            set {
                this.authorizationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public string AvsMessage {
            get {
                return this.avsMessageField;
            }
            set {
                this.avsMessageField = value;
            }
        }
        
        /// <remarks/>
        public string AvsReturnCode {
            get {
                return this.avsReturnCodeField;
            }
            set {
                this.avsReturnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> AvsStatus {
            get {
                return this.avsStatusField;
            }
            set {
                this.avsStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CancelAmount {
            get {
                return this.cancelAmountField;
            }
            set {
                this.cancelAmountField = value;
            }
        }
        
        /// <remarks/>
        public string CancelOrderId {
            get {
                return this.cancelOrderIdField;
            }
            set {
                this.cancelOrderIdField = value;
            }
        }
        
        /// <remarks/>
        public string CancelMessage {
            get {
                return this.cancelMessageField;
            }
            set {
                this.cancelMessageField = value;
            }
        }
        
        /// <remarks/>
        public string CancelReturnCode {
            get {
                return this.cancelReturnCodeField;
            }
            set {
                this.cancelReturnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> CancelStatus {
            get {
                return this.cancelStatusField;
            }
            set {
                this.cancelStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CancelTransactionId {
            get {
                return this.cancelTransactionIdField;
            }
            set {
                this.cancelTransactionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/webservice/pagador")]
    public partial class PagadorOneDollarAuthRequest {
        
        private System.Guid merchantIdField;
        
        private string orderIdField;
        
        private int amountField;
        
        private short paymentMethodField;
        
        private string cardHolderField;
        
        private string cardNumberField;
        
        private string cardExpirationDateField;
        
        private string cardSecurityCodeField;
        
        private bool useAvsField;
        
        private string cpfField;
        
        private string addressField;
        
        private string addressNumberField;
        
        private string addressComplementField;
        
        private string zipCode1Field;
        
        private string zipCode2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string countryField;
        
        /// <remarks/>
        public System.Guid MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
            }
        }
        
        /// <remarks/>
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public short PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        public string CardHolder {
            get {
                return this.cardHolderField;
            }
            set {
                this.cardHolderField = value;
            }
        }
        
        /// <remarks/>
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CardExpirationDate {
            get {
                return this.cardExpirationDateField;
            }
            set {
                this.cardExpirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string CardSecurityCode {
            get {
                return this.cardSecurityCodeField;
            }
            set {
                this.cardSecurityCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool UseAvs {
            get {
                return this.useAvsField;
            }
            set {
                this.useAvsField = value;
            }
        }
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string AddressNumber {
            get {
                return this.addressNumberField;
            }
            set {
                this.addressNumberField = value;
            }
        }
        
        /// <remarks/>
        public string AddressComplement {
            get {
                return this.addressComplementField;
            }
            set {
                this.addressComplementField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode1 {
            get {
                return this.zipCode1Field;
            }
            set {
                this.zipCode1Field = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode2 {
            get {
                return this.zipCode2Field;
            }
            set {
                this.zipCode2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/webservice/pagador")]
    public partial class PagadorVoidReturn {
        
        private System.Nullable<decimal> amountField;
        
        private string orderIdField;
        
        private string messageField;
        
        private string returnCodeField;
        
        private System.Nullable<byte> statusField;
        
        private string transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/webservice/pagador")]
    public partial class AuthorizeWithDateFirstInstallmentRequest {
        
        private System.Guid merchantIdField;
        
        private string orderIdField;
        
        private string customerNameField;
        
        private string amountField;
        
        private int paymentMethodField;
        
        private string holderField;
        
        private long cardNumberField;
        
        private string expirationField;
        
        private int securityCodeField;
        
        private int numberPaymentsField;
        
        private int typePaymentField;
        
        private System.DateTime dateFirstInstallmentField;
        
        /// <remarks/>
        public System.Guid MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
            }
        }
        
        /// <remarks/>
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public int PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        public string Holder {
            get {
                return this.holderField;
            }
            set {
                this.holderField = value;
            }
        }
        
        /// <remarks/>
        public long CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
            }
        }
        
        /// <remarks/>
        public int SecurityCode {
            get {
                return this.securityCodeField;
            }
            set {
                this.securityCodeField = value;
            }
        }
        
        /// <remarks/>
        public int NumberPayments {
            get {
                return this.numberPaymentsField;
            }
            set {
                this.numberPaymentsField = value;
            }
        }
        
        /// <remarks/>
        public int TypePayment {
            get {
                return this.typePaymentField;
            }
            set {
                this.typePaymentField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateFirstInstallment {
            get {
                return this.dateFirstInstallmentField;
            }
            set {
                this.dateFirstInstallmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/webservice/pagador")]
    public partial class PagadorAvsReturn : PagadorReturn {
        
        private string avsReturnCodeField;
        
        private string avsMessageField;
        
        private System.Nullable<byte> avsStatusField;
        
        /// <remarks/>
        public string avsReturnCode {
            get {
                return this.avsReturnCodeField;
            }
            set {
                this.avsReturnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string avsMessage {
            get {
                return this.avsMessageField;
            }
            set {
                this.avsMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> avsStatus {
            get {
                return this.avsStatusField;
            }
            set {
                this.avsStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AuthorizeCompletedEventHandler(object sender, AuthorizeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthorizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthorizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagadorReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagadorReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AuthorizeWithDateFirstInstallmentCompletedEventHandler(object sender, AuthorizeWithDateFirstInstallmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthorizeWithDateFirstInstallmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthorizeWithDateFirstInstallmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagadorReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagadorReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AuthorizeMobileCompletedEventHandler(object sender, AuthorizeMobileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthorizeMobileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthorizeMobileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagadorReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagadorReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AuthorizeMobilePartialCompletedEventHandler(object sender, AuthorizeMobilePartialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthorizeMobilePartialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthorizeMobilePartialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagadorReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagadorReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AuthorizeWithServiceTaxCompletedEventHandler(object sender, AuthorizeWithServiceTaxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthorizeWithServiceTaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthorizeWithServiceTaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagadorReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagadorReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AuthorizeAvsCompletedEventHandler(object sender, AuthorizeAvsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthorizeAvsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthorizeAvsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagadorAvsReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagadorAvsReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AuthorizeAvsStatusCompletedEventHandler(object sender, AuthorizeAvsStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthorizeAvsStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthorizeAvsStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagadorAvsReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagadorAvsReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VoidTransactionCompletedEventHandler(object sender, VoidTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoidTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoidTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagadorVoidReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagadorVoidReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VoidPartialCompletedEventHandler(object sender, VoidPartialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoidPartialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoidPartialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagadorVoidReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagadorVoidReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void OneDollarAuthCompletedEventHandler(object sender, OneDollarAuthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OneDollarAuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OneDollarAuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagadorOneDollarAuthResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagadorOneDollarAuthResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AuthorizeExistingAvsStatusWithServiceCompletedEventHandler(object sender, AuthorizeExistingAvsStatusWithServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthorizeExistingAvsStatusWithServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthorizeExistingAvsStatusWithServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagadorReturnWithService Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagadorReturnWithService)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CaptureCompletedEventHandler(object sender, CaptureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CaptureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CaptureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagadorReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagadorReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CapturePartialCompletedEventHandler(object sender, CapturePartialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CapturePartialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CapturePartialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagadorReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagadorReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateTransactionCompletedEventHandler(object sender, CreateTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Guid Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591