//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrimFuel.WebServices.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/trimfuel/SaleService.asmx")]
        public string TrimFuel_WebServices_Test_SaleWebService_SaleService_ {
            get {
                return ((string)(this["TrimFuel_WebServices_Test_SaleWebService_SaleService_"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://app02.3plcentral.com/WebServiceExternal/Contracts.asmx")]
        public string TrimFuel_WebServices_Test_com_3plcentral_ServiceExternal {
            get {
                return ((string)(this["TrimFuel_WebServices_Test_com_3plcentral_ServiceExternal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dashboard.trianglecrm.com/support/customer_service_feed.asmx")]
        public string TrimFuel_WebServices_Test_com_trianglecrm_dashboard_customer_service_feed {
            get {
                return ((string)(this["TrimFuel_WebServices_Test_com_trianglecrm_dashboard_customer_service_feed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://trimfuel.localhost/support/customer_service_feed.asmx")]
        public string TrimFuel_WebServices_Test_localhost_trimfuel_customer_service_feed {
            get {
                return ((string)(this["TrimFuel_WebServices_Test_localhost_trimfuel_customer_service_feed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://trimfuel.localhost/api/billing_ws.asmx")]
        public string TrimFuel_WebServices_Test_localhost_trimfuel1_billing_ws {
            get {
                return ((string)(this["TrimFuel_WebServices_Test_localhost_trimfuel1_billing_ws"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://jmb.trianglecrm.com/api/billing_ws.asmx")]
        public string TrimFuel_WebServices_Test_com_trianglecrm_jmb_billing_ws {
            get {
                return ((string)(this["TrimFuel_WebServices_Test_com_trianglecrm_jmb_billing_ws"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://client1.localhost/api/billing_ws.asmx")]
        public string TrimFuel_WebServices_Test_localhost_client1_billing_ws {
            get {
                return ((string)(this["TrimFuel_WebServices_Test_localhost_client1_billing_ws"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://directaction.trianglecrm.com/api/billing_ws.asmx")]
        public string TrimFuel_WebServices_Test_com_trianglecrm_directaction_billing_ws {
            get {
                return ((string)(this["TrimFuel_WebServices_Test_com_trianglecrm_directaction_billing_ws"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://learn2befree.trianglecrm.com/api/billing_ws.asmx")]
        public string TrimFuel_WebServices_Test_com_trianglecrm_learn2befree_billing_ws {
            get {
                return ((string)(this["TrimFuel_WebServices_Test_com_trianglecrm_learn2befree_billing_ws"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dashboard.trianglecrm.com/api/billing_ws.asmx")]
        public string TrimFuel_WebServices_Test_com_trianglecrm_dashboard1_billing_ws {
            get {
                return ((string)(this["TrimFuel_WebServices_Test_com_trianglecrm_dashboard1_billing_ws"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://coaction.trianglecrm.com/api/billing_ws.asmx")]
        public string TrimFuel_WebServices_Test_com_trianglecrm_coaction_billing_ws {
            get {
                return ((string)(this["TrimFuel_WebServices_Test_com_trianglecrm_coaction_billing_ws"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apex.trianglecrm.com/api/billing_ws.asmx")]
        public string TrimFuel_WebServices_Test_com_trianglecrm_apex_billing_ws {
            get {
                return ((string)(this["TrimFuel_WebServices_Test_com_trianglecrm_apex_billing_ws"]));
            }
        }
    }
}
